# Tên quy trình: Xây dựng và triển khai trang Astro lên GitHub Pages
name: Deploy Astro site to Pages

on:
  # Chạy mỗi khi có commit mới vào nhánh main
  push:
    branches: [main]

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền cho GITHUB_TOKEN để triển khai lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một lần triển khai cùng lúc
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lấy mã nguồn về
        uses: actions/checkout@v4

      - name: 2. Cài đặt pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: 3. Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm # <-- Chỉ định rõ cache cho pnpm

      - name: 4. Cài đặt các gói phụ thuộc
        run: pnpm install

      - name: 5. Xây dựng trang web bằng Astro
        run: pnpm build

      - name: 6. Tải lên sản phẩm đã xây dựng
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Phải chờ job 'build' chạy xong
    steps:
      - name: Triển khai lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
